### ISSUE TITLE
Error installing github version on windows10

### ISSUE THREAD

**Issue by SansMorel** [dibbelab/gficf#1]
Hi, 

I had some issues installing the github version. The problem seemed to be that the gsl libraries were incompatible. Possibly a 32bit issue?
I followed this guide 
https://stackoverflow.com/questions/23640088/setting-up-rcpp-gsl-for-windows/23666023#23666023
but using local323.zip instead of local300.zip, exporting it and then running 
`Sys.setenv(GSL_LIBS = '"C:/Program Files/R/local323"')`
before installation seemed to do the trick.

**Comment by dibbelab** [comment]
thanks for pointing this out. I did not have 32bit machine on which to test it, but I will update the README
