### ISSUE TITLE
Can't install gficf v2

### ISSUE THREAD

**Issue by jyjysea** [dibbelab/gficf#7]
g++ -shared -s -static-libgcc -o gficf.dll tmp.def ModularityOptimizer.o RModularityOptimizer.o RcppExports.o detectCores.o jaccard_coeff.o mann_whitney.o misc.o rcpp_mann_whitney.o rcpp_parallel_jaccard_coeff.o rcpp_parallel_mann_whitney.o -L/lib/x64 -lgsl -lgslcblas -LC:/Users/jianj/AppData/Local/R/win-library/4.3/RcppParallel/lib/x64 -ltbb -ltbbmalloc -fopenmp -LC:/RBuildTools/4.3/x86_64-w64-mingw32.static.posix/lib/x64 -LC:/RBuildTools/4.3/x86_64-w64-mingw32.static.posix/lib -LC:/PROGRA~1/R/R-43~1.0/bin/x64 -lR
C:\RBuildTools\4.3\x86_64-w64-mingw32.static.posix\bin/ld.exe: misc.o:misc.cpp:(.text.hot+0x1c5): undefined reference to `dgemm_'
C:\RBuildTools\4.3\x86_64-w64-mingw32.static.posix\bin/ld.exe: misc.o:misc.cpp:(.text.hot+0x2aa): undefined reference to `dgemv_'
C:\RBuildTools\4.3\x86_64-w64-mingw32.static.posix\bin/ld.exe: misc.o:misc.cpp:(.text.hot+0x607): undefined reference to `dsyrk_'
collect2.exe: error: ld returned 1 exit status
no DLL was created
ERROR: compilation failed for package 'gficf'

**Comment by jyjysea** [comment]
gficf v1 can be good installed, but can't install gficf v2 using command "remotes::install_github("gambalab/gficf")".

Please help!! Thanks a lot!

**Comment by gambalab** [comment]
I am sorry for this, but you have to install gficfv2 on a linux machine and everything will work smoothly. It is the only OS that we officially support, because I don t have access to a windows machine and I can t test. Then the other problem is that windows has too many variables.

**Comment by gambalab** [comment]
Just for curiosity, try to fork (or clone) and add at the end of Makevars.win the following line:

`PKG_LIBS += $(LAPACK_LIBS) $(BLAS_LIBS) $(FLIBS)`

and then install it.

**Comment by ne0devil** [comment]
Yes I was getting the same error and adding the libs to the Makevars.win worked for me, I created a fork and then changed the installation command to use my fork
```
# Install gficf from github
if(!require(devtools)){ install.packages("devtools")}
devtools::install_github("ne0devil/gficf-win")
```

**Comment by gambalab** [comment]
good! .. I will commit this change also on my github.. thank you for testing :)
